name: CD Build

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup Java JDK 11
      uses: actions/setup-java@v2.3.0
      with:
        java-version: 11
        distribution: "temurin"
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Setup NUKE
      run: dotnet tool install Nuke.GlobalTool --global
    - name: Install Workloads
      # TODO: This is slow. Maybe we can make a docker container with this already done?
      run: dotnet workload install android android-aot ios maccatalyst maui
    - name: Pack
      run: nuke Pack --msbuild-properties ContinuousIntegrationBuild=true SilkEnableSourceLink=true --feature-sets Legacy-Android Legacy-iOS
    - name: Upload Unsigned Artifacts to Actions
      uses: actions/upload-artifact@v2.2.4
      with:
        name: unsigned_nupkgs
        path: "build/output_packages/*.nupkg"
        if-no-files-found: warn
        retention-days: 1
    - name: Push to NuGet
      run: nuke SignPackages PushToNuGet --skip Clean Restore Pack --configuration Release --msbuild-properties ContinuousIntegrationBuild=true SilkEnableSourceLink=true --feature-sets Android iOS --nuget-api-key ${{ secrets.NUGET_TOKEN }} --sign-username "${{ secrets.SIGN_USERNAME }}" --sign-password "${{ secrets.SIGN_PASSWORD }}"
    - name: Upload Signed Artifacts to Actions
      uses: actions/upload-artifact@v2.2.4
      with:
        name: signed_nupkgs
        path: "build/output_packages/*.nupkg"
        if-no-files-found: warn
